{{- if .Values.apiServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssvirt.fullname" . }}-api-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssvirt.apiServerLabels" . | nindent 4 }}
  {{- with .Values.apiServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "ssvirt.annotations" .) }}
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiServer.service.type }}
  ports:
    - port: {{ .Values.apiServer.service.port }}
      targetPort: {{ .Values.apiServer.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ssvirt.apiServerSelectorLabels" . | nindent 4 }}
{{- end }}
