{{- if .Values.apiServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssvirt.fullname" . }}-api-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssvirt.apiServerLabels" . | nindent 4 }}
  {{- with (include "ssvirt.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.apiServer.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "ssvirt.apiServerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ssvirt.apiServerSelectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with (include "ssvirt.annotations" .) }}
        {{- . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ssvirt.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.apiServer.terminationGracePeriodSeconds | default 30 }}
      securityContext:
        runAsNonRoot: true
        fsGroup: 1001
      containers:
        - name: api-server
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          image: {{ include "ssvirt.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/api-server
          ports:
            - name: http
              containerPort: {{ .Values.apiServer.service.targetPort }}
              protocol: TCP
          env:
            - name: SSVIRT_API_PORT
              value: {{ .Values.apiServer.service.targetPort | quote }}
            - name: SSVIRT_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: database-url
            - name: SSVIRT_AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: jwt-secret
            - name: SSVIRT_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: log-level
            - name: SSVIRT_LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: log-format
            - name: SSVIRT_DATABASE_MAX_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: database-max-connections
            - name: SSVIRT_DATABASE_MAX_IDLE_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: database-max-idle-connections
            - name: SSVIRT_DATABASE_CONN_MAX_LIFETIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: database-conn-max-lifetime
            - name: SSVIRT_DATABASE_CONN_MAX_IDLE_TIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: database-conn-max-idle-time
            - name: SSVIRT_AUTH_TOKEN_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: auth-token-expiry
            - name: SSVIRT_KUBERNETES_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: kubernetes-namespace
          {{- with .Values.apiServer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiServer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.apiServer.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config-dir
              mountPath: /etc/ssvirt
              readOnly: true
      volumes:
        - name: tmp
          emptyDir: {}
        - name: config-dir
          configMap:
            name: {{ include "ssvirt.fullname" . }}-config
      {{- with .Values.apiServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
