apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ssvirt.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssvirt.labels" . | nindent 4 }}
  {{- with (include "ssvirt.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  # Logging configuration
  log-level: {{ .Values.logging.level | quote }}
  log-format: {{ .Values.logging.format | quote }}

  # Database configuration
  database-max-connections: {{ .Values.database.maxConnections | quote }}
  database-max-idle-connections: {{ .Values.database.maxIdleConnections | quote }}
  database-conn-max-lifetime: {{ .Values.database.connMaxLifetime | quote }}
  database-conn-max-idle-time: {{ .Values.database.connMaxIdleTime | quote }}

  # Authentication configuration
  auth-token-expiry: {{ .Values.auth.tokenExpiry | quote }}

  # Kubernetes configuration
  kubernetes-namespace: {{ .Values.kubernetes.namespace | quote }}

  # Application configuration file (YAML format)
  config.yaml: |
    database:
      max_connections: {{ .Values.database.maxConnections }}
      max_idle_connections: {{ .Values.database.maxIdleConnections }}
      conn_max_lifetime: {{ .Values.database.connMaxLifetime }}
      conn_max_idle_time: {{ .Values.database.connMaxIdleTime }}

    api:
      port: {{ .Values.apiServer.service.targetPort }}

    auth:
      token_expiry: {{ .Values.auth.tokenExpiry }}

    kubernetes:
      namespace: {{ .Values.kubernetes.namespace }}

    log:
      level: {{ .Values.logging.level }}
      format: {{ .Values.logging.format }}

    {{- with .Values.config.extra }}
    # Additional configuration
    {{- toYaml . | nindent 4 }}
    {{- end }}

