{{- if .Values.controller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssvirt.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssvirt.controllerLabels" . | nindent 4 }}
  {{- with (include "ssvirt.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  strategy:
    type: Recreate  # Controller should not have multiple replicas running simultaneously
  selector:
    matchLabels:
      {{- include "ssvirt.controllerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ssvirt.controllerSelectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with (include "ssvirt.annotations" .) }}
        {{- . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ssvirt.controllerServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
        - name: controller
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: {{ include "ssvirt.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/controller
          ports:
            - name: metrics
              containerPort: 8081
              protocol: TCP
          env:
            - name: SSVIRT_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: database-url
            - name: SSVIRT_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: log-level
            - name: SSVIRT_LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: log-format
            - name: SSVIRT_DATABASE_MAX_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: database-max-connections
            - name: SSVIRT_DATABASE_MAX_IDLE_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: database-max-idle-connections
            - name: SSVIRT_DATABASE_CONN_MAX_LIFETIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: database-conn-max-lifetime
            - name: SSVIRT_DATABASE_CONN_MAX_IDLE_TIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: database-conn-max-idle-time
            - name: SSVIRT_KUBERNETES_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ssvirt.fullname" . }}-config
                  key: kubernetes-namespace
          {{- with .Values.controller.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.controller.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config-dir
              mountPath: /etc/ssvirt
              readOnly: true
      volumes:
        - name: tmp
          emptyDir: {}
        - name: config-dir
          configMap:
            name: {{ include "ssvirt.fullname" . }}-config
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
