{{- if and .Values.ingress.enabled .Values.apiServer.enabled (not .Values.route.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ssvirt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssvirt.apiServerLabels" . | nindent 4 }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "ssvirt.annotations" .) }}
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "ssvirt.fullname" $ }}-api-server
                port:
                  number: {{ $.Values.apiServer.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
