apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssvirt.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssvirt.labels" . | nindent 4 }}
  {{- with (include "ssvirt.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  # Database connection parameters
  database-host: {{ include "ssvirt.databaseHost" . | b64enc | quote }}
  database-port: {{ include "ssvirt.databasePort" . | b64enc | quote }}
  database-username: {{ include "ssvirt.databaseUsername" . | b64enc | quote }}
  database-database: {{ include "ssvirt.databaseName" . | b64enc | quote }}
  database-sslmode: {{ "disable" | b64enc | quote }}

  # JWT Secret
  jwt-secret: {{ include "ssvirt.jwtSecret" . | b64enc | quote }}

---
{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) .Values.externalDatabase.password }}
# External database secret (only created when using external DB without existing secret)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssvirt.fullname" . }}-external-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssvirt.labels" . | nindent 4 }}
  {{- with (include "ssvirt.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}

---
{{- if and .Values.initialAdmin.enabled .Values.initialAdmin.autoGenerate }}
{{- $secretName := .Values.initialAdmin.secretName | default "ssvirt-initial-admin-generated" }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if not $existingSecret }}
# Initial admin auto-generated secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssvirt.labels" . | nindent 4 }}
    app.kubernetes.io/component: initial-admin
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: {{ .Values.initialAdmin.username | default "admin" | b64enc }}
  password: {{ randAscii 32 | b64enc }}
  email: {{ .Values.initialAdmin.email | default "admin@example.com" | b64enc }}
  first_name: {{ .Values.initialAdmin.firstName | default "System" | b64enc }}
  last_name: {{ .Values.initialAdmin.lastName | default "Administrator" | b64enc }}
{{- end }}
{{- end }}

