{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ssvirt.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssvirt.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "ssvirt.annotations" .) }}
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true

---
# Controller service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ssvirt.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssvirt.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "ssvirt.annotations" .) }}
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}