apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssvirt-organization-controller
  namespace: ssvirt-system
  labels:
    app.kubernetes.io/name: ssvirt
    app.kubernetes.io/component: organization-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ssvirt-organization-controller
  labels:
    app.kubernetes.io/name: ssvirt
    app.kubernetes.io/component: organization-controller
rules:
# Namespace management permissions
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
# ServiceAccounts in managed namespaces
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# Secrets in managed namespaces  
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# ConfigMaps in managed namespaces
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# ResourceQuotas for VDC management
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# LimitRanges for VDC management
- apiGroups: [""]
  resources: ["limitranges"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# NetworkPolicies for tenant isolation
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# RBAC for tenant permissions
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# OpenShift Virtualization resources
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachines", "virtualmachineinstances"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["instancetype.kubevirt.io"]
  resources: ["virtualmachineinstancetypes", "virtualmachineclusterinstancetypes"]
  verbs: ["get", "list", "watch"]
# OpenShift networking
- apiGroups: ["k8s.ovn.org"]
  resources: ["userdefinednetworks"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ssvirt-organization-controller
  labels:
    app.kubernetes.io/name: ssvirt
    app.kubernetes.io/component: organization-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ssvirt-organization-controller
subjects:
- kind: ServiceAccount
  name: ssvirt-organization-controller
  namespace: ssvirt-system